language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
      mono: none
      dotnet: 3.0
    - os: windows
      mono: none

git:
  depth: 3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned';
    fi
install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      powershell -Command '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 3.0 -InstallDir "C:/Program Files/dotnet"';
      powershell ".travis/pvs-install.ps1 -username ${PVS_USERNAME} -key ${PVS_KEY}";
    fi
  - dotnet restore
script:
  - dotnet build
  - dotnet test Nandaka.Tests/Nandaka.Tests.csproj
after_success:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      powershell ".travis/pvs-analyze.ps1 -target Nandaka/Nandaka.csproj -mailFrom ${AUTOPOST_MAIL} -password ${AUTOPOST_PASSWORD} -mailTo ${OWNER_MAIL}";
    fi